#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

function show_help {
    echo -e "${YELLOW}OptiFlow CLI Manager${NC}"
    echo "Uso:"
    echo "  ./opti s              -> Inicia TUDO (builda se necessário)"
    echo "  ./opti stop all       -> Para e remove todos os containers"
    echo "  ./opti start <nome>   -> Inicia apenas um container específico"
    echo "  ./opti stop <nome>    -> Para apenas um container específico"
    echo "  ./opti logs <nome>    -> Vê os logs de um container"
    echo "  ./opti list           -> Lista o status dos containers"
}

case "$1" in
    "s")
        echo -e "${GREEN} Iniciando todo o ecossistema OptiFlow...${NC}"
        docker compose up -d --build --remove-orphans
        echo -e "${GREEN} Tudo rodando! Use './opti list' para verificar.${NC}"
        ;;
    
    "stop")
        if [ "$2" == "all" ]; then
            echo -e "${RED} Parando todo o sistema...${NC}"
            docker compose down
        elif [ -n "$2" ]; then
            echo -e "${YELLOW} Parando o serviço: $2...${NC}"
            docker compose stop "$2"
        else
            echo "Erro: Especifique 'all' ou o nome do serviço."
        fi
        ;;

    "start")
        if [ -n "$2" ]; then
            echo -e "${GREEN} Iniciando serviço: $2...${NC}"
            docker compose up -d "$2"
        else
            echo "Erro: Digite o nome do container. Ex: ./opti start user-api"
        fi
        ;;

    "logs")
        if [ -n "$2" ]; then
            docker compose logs -f "$2"
        else
            docker compose logs -f
        fi
        ;;

    "list")
        docker compose ps
        ;;

    *)
        show_help
        ;;
esac